[project]
name = "milp-final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gurobipy>=13.0.1",
    "ipykernel>=7.2.0",
    "numpy>=2.4.2",
]
